[build]
  command = "npm run build"
  publish = ".next"

[functions]
  included_files = ["models/**"]

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[headers]]
  for = "/widget.js"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET"
    Content-Type = "application/javascript"

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"
