'use client';
import Link from 'next/link';
import { ArrowLeft, Scale, Gavel, FileText } from 'lucide-react';

export default function TermsConditions() {
  return (
    <div className="min-h-screen bg-background py-12 px-4 sm:px-6">
      <div className="max-w-3xl mx-auto">
        <div className="mb-8">
          <Link href="/" className="inline-flex items-center text-sm text-muted-foreground hover:text-primary mb-4 group">
            <ArrowLeft className="mr-2 h-4 w-4 group-hover:-translate-x-1 transition-transform" /> Back to Home
          </Link>
          <div className="flex items-center gap-3 mb-2">
             <div className="p-2 rounded-xl bg-primary/10 text-primary"><Scale className="h-6 w-6"/></div>
             <h1 className="text-3xl font-bold tracking-tight">Terms of Service</h1>
          </div>
          <p className="text-muted-foreground text-sm">Effective: May 11, 2026</p>
        </div>

        <div className="prose prose-gray dark:prose-invert max-w-none border-t pt-8 space-y-6 text-muted-foreground leading-relaxed">
          <section>
            <h2 className="text-xl font-semibold text-foreground">1. Provision of Service</h2>
            <p>Keli AI grants users license to operate, configure, and install discrete client-facing inference chat nodes governed by workspace restrictions. Users retain definitive responsibility for output content generated by tuned agents.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground">2. Prohibited Abuse</h2>
            <p>System degradation, scraping automation, denial of inference cycles, and illicit content proliferation using embedded widgets guarantees instantaneous permanent account banishment without credit refunds.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground">3. B2B Limitations</h2>
            <p>Platform stability is aimed at high-fidelity operations; however, Keli AI bears no liability for inaccurate hallucinated responses furnished by generated entities impacting consumer commercial operations.</p>
          </section>
        </div>
      </div>
    </div>
  );
}
