const fs = require('fs');
const path = require('path');

const filePath = path.join(__dirname, '../src/app/deploy/page.tsx');
let content = fs.readFileSync(filePath, 'utf-8');

const replacements = [
  // Header
  ['text-[11px] font-semibold text-orange-600 tracking-wider', 'text-[11px] font-semibold text-orange-600 dark:text-orange-400 tracking-wider'],
  ['<h1 className="text-3xl font-semibold text-gray-900 tracking-tight">', '<h1 className="text-3xl font-semibold text-gray-900 dark:text-zinc-100 tracking-tight">'],
  ['<p className="text-[14px] text-gray-500 mt-1.5">', '<p className="text-[14px] text-gray-500 dark:text-zinc-400 mt-1.5">'],
  ['inline-flex items-center gap-2 bg-emerald-50 border border-emerald-100 text-emerald-700 px-3 py-1.5 rounded-full', 'inline-flex items-center gap-2 bg-emerald-50 dark:bg-emerald-950/30 border border-emerald-100 dark:border-emerald-900/30 text-emerald-700 dark:text-emerald-400 px-3 py-1.5 rounded-full'],
  
  // Method selection buttons
  ["isAct ? 'border-orange-500 bg-orange-50/30 shadow-sm ring-1 ring-orange-500' : 'border-gray-200 bg-white hover:border-gray-300 hover:shadow-sm'", "isAct ? 'border-orange-500 dark:border-orange-500/50 bg-orange-50/30 dark:bg-orange-950/20 shadow-sm ring-1 ring-orange-500' : 'border-gray-200 dark:border-zinc-800 bg-white dark:bg-zinc-900 hover:border-gray-300 dark:hover:border-zinc-700 hover:shadow-sm'"],
  ['className={`w-10 h-10 rounded-xl flex items-center justify-center mb-4 transition-colors ${isAct ? \'bg-orange-500 text-white\' : \'bg-gray-50 text-gray-500\'}`}', 'className={`w-10 h-10 rounded-xl flex items-center justify-center mb-4 transition-colors ${isAct ? \'bg-orange-500 text-white\' : \'bg-gray-50 dark:bg-zinc-800 text-gray-500 dark:text-zinc-400\'}`}'],
  ['<div className="font-semibold text-[14px] text-gray-900 mb-1">', '<div className="font-semibold text-[14px] text-gray-900 dark:text-zinc-100 mb-1">'],
  ['<div className="text-[11px] text-gray-500 leading-relaxed">', '<div className="text-[11px] text-gray-500 dark:text-zinc-400 leading-relaxed">'],
  ['className="absolute top-3 right-3 bg-white text-[9px] font-bold uppercase tracking-wide px-1.5 py-0.5 rounded-md border shadow-sm text-gray-600"', 'className="absolute top-3 right-3 bg-white dark:bg-zinc-800 text-[9px] font-bold uppercase tracking-wide px-1.5 py-0.5 rounded-md border dark:border-zinc-700 shadow-sm text-gray-600 dark:text-zinc-300"'],
  
  // Card container
  ['className="bg-white border border-gray-200 rounded-[24px] p-6 sm:p-8 shadow-sm"', 'className="bg-white dark:bg-zinc-900 border border-gray-200 dark:border-zinc-800 rounded-[24px] p-6 sm:p-8 shadow-sm"'],
  ['<h2 className="text-[16px] font-semibold text-gray-900 capitalize">', '<h2 className="text-[16px] font-semibold text-gray-900 dark:text-zinc-100 capitalize">'],
  ['<p className="text-[13px] text-gray-500 mt-1">', '<p className="text-[13px] text-gray-500 dark:text-zinc-400 mt-1">'],
  
  // Step Visualization
  ['className="space-y-4 border-l-2 border-gray-100 ml-3 pl-6 relative"', 'className="space-y-4 border-l-2 border-gray-100 dark:border-zinc-800 ml-3 pl-6 relative"'],
  ['bg-orange-500 rounded-full ring-4 ring-white', 'bg-orange-500 rounded-full ring-4 ring-white dark:ring-zinc-900'],
  ['<div className="text-[13px] font-semibold text-gray-900">Copy code snippet</div>', '<div className="text-[13px] font-semibold text-gray-900 dark:text-zinc-100">Copy code snippet</div>'],
  ['<div className="text-[12px] text-gray-500 mt-0.5">Copy the autogenerated', '<div className="text-[12px] text-gray-500 dark:text-zinc-400 mt-0.5">Copy the autogenerated'],
  
  ['bg-gray-200 rounded-full ring-4 ring-white', 'bg-gray-200 dark:bg-zinc-800 rounded-full ring-4 ring-white dark:ring-zinc-900'],
  ['<div className="text-[13px] font-semibold text-gray-900">Paste before &lt;/body&gt;</div>', '<div className="text-[13px] font-semibold text-gray-900 dark:text-zinc-100">Paste before &lt;/body&gt;</div>'],
  ['<div className="text-[12px] text-gray-500 mt-0.5">Insert standard tag', '<div className="text-[12px] text-gray-500 dark:text-zinc-400 mt-0.5">Insert standard tag'],
  ['<div className="text-[13px] font-semibold text-gray-900">Go live</div>', '<div className="text-[13px] font-semibold text-gray-900 dark:text-zinc-100">Go live</div>'],
  ['<div className="text-[12px] text-gray-500 mt-0.5">Publish settings to deploy', '<div className="text-[12px] text-gray-500 dark:text-zinc-400 mt-0.5">Publish settings to deploy'],

  // Domain panel
  ['className="bg-white border border-gray-200 rounded-[24px] p-6 shadow-sm"', 'className="bg-white dark:bg-zinc-900 border border-gray-200 dark:border-zinc-800 rounded-[24px] p-6 shadow-sm"'],
  ['<h3 className="text-[15px] font-semibold text-gray-900 flex items-center gap-2 mb-1">', '<h3 className="text-[15px] font-semibold text-gray-900 dark:text-zinc-100 flex items-center gap-2 mb-1">'],
  ['<p className="text-[12px] text-gray-500 mb-5 leading-relaxed">', '<p className="text-[12px] text-gray-500 dark:text-zinc-400 mb-5 leading-relaxed">'],
  ['className="flex-1 min-w-0 bg-gray-50 border border-gray-200 rounded-xl px-3 py-2 text-[13px] font-medium text-gray-800 focus:bg-white focus:border-orange-400 focus:ring-[3px] focus:ring-orange-500/10 transition-all outline-none placeholder:text-gray-400"', 'className="flex-1 min-w-0 bg-gray-50 dark:bg-zinc-950 border border-gray-200 dark:border-zinc-800 rounded-xl px-3 py-2 text-[13px] font-medium text-gray-800 dark:text-zinc-100 focus:bg-white dark:focus:bg-zinc-900 focus:border-orange-400 focus:ring-[3px] focus:ring-orange-500/10 transition-all outline-none placeholder:text-gray-400"'],
  ['className="bg-gray-900 text-white rounded-xl w-10 flex items-center justify-center hover:bg-black transition-all disabled:opacity-50 shadow-sm shrink-0"', 'className="bg-gray-900 dark:bg-zinc-100 text-white dark:text-zinc-900 rounded-xl w-10 flex items-center justify-center hover:bg-black dark:hover:bg-white transition-all disabled:opacity-50 shadow-sm shrink-0"'],
  
  // List items
  ['className="flex items-center justify-between bg-gray-50 border border-gray-100 px-3 py-2 rounded-xl group transition-colors"', 'className="flex items-center justify-between bg-gray-50 dark:bg-zinc-950 border border-gray-100 dark:border-zinc-850 px-3 py-2 rounded-xl group transition-colors"'],
  ['<span className="text-[12px] font-medium text-gray-700 truncate">{d}</span>', '<span className="text-[12px] font-medium text-gray-700 dark:text-zinc-300 truncate">{d}</span>'],
  ['className="opacity-0 group-hover:opacity-100 text-gray-400 hover:text-red-500 transition-all p-1"', 'className="opacity-0 group-hover:opacity-100 text-gray-400 dark:text-zinc-500 hover:text-red-500 dark:hover:text-red-400 transition-all p-1"'],
  ['className="text-[12px] text-gray-400 text-center py-4 border border-dashed border-gray-200 rounded-xl"', 'className="text-[12px] text-gray-400 dark:text-zinc-500 text-center py-4 border border-dashed border-gray-200 dark:border-zinc-800 rounded-xl"']
];

for (const [target, replacement] of replacements) {
  const cleanTarget = target.replace(/\r\n/g, '\n');
  const cleanReplacement = replacement.replace(/\r\n/g, '\n');
  
  if (content.includes(cleanTarget)) {
    content = content.split(cleanTarget).join(cleanReplacement);
  } else {
    const contentNormalized = content.replace(/\r\n/g, '\n');
    if (contentNormalized.includes(cleanTarget)) {
      content = contentNormalized.split(cleanTarget).join(cleanReplacement);
    } else {
      console.warn(`WARNING: Target not found in deploy page: ${cleanTarget.substring(0, 50)}...`);
    }
  }
}

fs.writeFileSync(filePath, content, 'utf-8');
console.log("Successfully updated Deploy page with dark mode overrides!");
